repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: file-contents-sorter
        files: ^requirements.in$
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
      - id: mypy
  - repo: https://github.com/doublify/pre-commit-rust
    rev: 55f3471
    hooks:
      - id: fmt
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports
