name: go

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
    - name: Run tests
      run: ls -d day*/part*-go | xargs -I {} bash -c "cd '{}' && go test"
