name: python

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: ls -d day* | xargs -I {} bash -c "cd '{}' && PYTHONPATH=. pytest part*.py"
